list(APPEND fvcom_mods_files
  FVCOM/src/mod_prec.F
  FVCOM/src/sinter.F
  FVCOM/src/mod_types.F
  FVCOM/src/mod_time.F
  FVCOM/src/mod_main.F
  FVCOM/src/mod_spherical.F
  FVCOM/src/mod_utils.F
  FVCOM/src/mod_clock.F
  FVCOM/src/eqs_of_state.F
  FVCOM/src/mod_interp.F
  FVCOM/src/mod_par.F
  FVCOM/src/mod_par_special.F
  FVCOM/src/mod_ncll.F
  FVCOM/src/mod_nctools.F
  FVCOM/src/mod_wd.F
  FVCOM/src/mod_sng.F
  FVCOM/src/mod_heatflux.F
  FVCOM/src/mod_solar.F
  FVCOM/src/mod_bulk.F
  FVCOM/src/mod_input.F
  FVCOM/src/mod_force.F
  FVCOM/src/mod_obcs.F
  FVCOM/src/mod_petsc.F
  FVCOM/src/mod_semi_implicit.F
  FVCOM/src/mod_non_hydro.F
  FVCOM/src/mod_set_time.F
  FVCOM/src/ice_kinds_mod.F
  FVCOM/src/ice_model_size.F
  FVCOM/src/ice_domain.F
  FVCOM/src/ice_constants.F
  FVCOM/src/ice_fileunits.F
  FVCOM/src/ice_state.F
  FVCOM/src/ice_work.F
  FVCOM/src/ice_grid.F
  FVCOM/src/ice_albedo.F
  FVCOM/src/ice_calendar.F
  FVCOM/src/ice_flux.F
  FVCOM/src/ice_flux_in.F
  FVCOM/src/ice_itd.F
  FVCOM/src/ice_mechred.F
  FVCOM/src/ice_itd_linear.F
  FVCOM/src/ice_scaling.F
  FVCOM/src/ice_atmo.F
  FVCOM/src/ice_ocean.F
  FVCOM/src/ice_therm_vertical.F
  FVCOM/src/ice_init.F
  FVCOM/src/ice_therm_itd.F
  FVCOM/src/mod_ice2d.F
  FVCOM/src/mod_ice.F
  FVCOM/src/mod_startup.F
  FVCOM/src/mod_wqm.F
  FVCOM/src/mod_ncdio.F
  FVCOM/src/mod_setup.F
  FVCOM/src/mod_newinp.F
  FVCOM/src/particle.F
  FVCOM/src/linklist.F
  FVCOM/src/mod_lag.F
  FVCOM/src/mod_northpole.F
  FVCOM/src/mod_pwp.F
  FVCOM/src/mod_dye.F
  FVCOM/src/mod_optimal_interpolation.F
  FVCOM/src/mod_report.F
  FVCOM/src/mod_probe.F
  FVCOM/src/mod_gotm.F
  FVCOM/src/mod_balance_2d.F
  FVCOM/src/mod_tridiag.F
  FVCOM/src/mod_scal.F
  FVCOM/src/mod_meanflow.F
  FVCOM/src/mod_obcs2.F
  FVCOM/src/mod_obcs3.F
  FVCOM/src/mod_sed.F
  FVCOM/src/mod_enkf.F
  FVCOM/src/mod_etkf.F
  FVCOM/src/mod_rrk.F
  FVCOM/src/mod_rrkf_obs.F
  FVCOM/src/mod_rrkassim.F
  FVCOM/src/mod_enkf_ncd.F
  FVCOM/src/enkf_ncdio.F
  FVCOM/src/mod_enkf_obs.F
  FVCOM/src/mod_enkfassim.F
  FVCOM/src/mod_assim.F
  FVCOM/src/mod_nesting.F
  FVCOM/src/mod_visit.F
  FVCOM/src/mod_plbc.F
  FVCOM/src/mod_dam.F
  FVCOM/src/mod_station_timeseries.F
  FVCOM/src/mod_sparse_timeseries.F
  FVCOM/src/mod_boundschk.F
  FVCOM/src/mod_esmf_nesting.F
  FVCOM/src/mod_cstms_vars.F
  FVCOM/src/mod_flocmod.F
  FVCOM/src/mod_sed_cstms.F
  FVCOM/src/mod_fluid_mud.F
  FVCOM/src/mod_tvd.F
  FVCOM/src/mod_mld_rho.F
  FVCOM/src/mod_vegetation.F
  FVCOM/src/mod_heatflux_sediment.F
  FVCOM/src/mod_vector_projection.F)

list(APPEND fvcom_modsw_files
  #FVCOM/src/mod_main_wave.F
  FVCOM/src/swmod1.F
  FVCOM/src/swmod2.F
  FVCOM/src/swmod3.F
  FVCOM/src/mod_action_im.F
  FVCOM/src/mod_action_ex.F
  FVCOM/src/mod_wavesetup.F
  FVCOM/src/mod_wave_current_interaction.F
  FVCOM/src/mod_bbl.F)

list(APPEND fvcom_main_files
  #FVCOM/srcfvcom.F
  FVCOM/src/genmap.F
  FVCOM/src/tge.F
  FVCOM/src/longshore_flow.F
  FVCOM/src/cell_area.F
  FVCOM/src/open_all.F
  FVCOM/src/load_grid.F
  FVCOM/src/allocate_all.F
  FVCOM/src/setup_domain.F
  FVCOM/src/genmap_obc.F
  FVCOM/src/genmap_lsf.F
  FVCOM/src/print_vals.F
  FVCOM/src/coords_n_const.F
  FVCOM/src/shape_coef_gcn.F
  FVCOM/src/shape_coef_gcy.F
  FVCOM/src/depth_grad.F
  FVCOM/src/grid_metrics.F
  FVCOM/src/cntrl_prmtrs.F
  FVCOM/src/init_sed.F
  FVCOM/src/internal_step.F
  FVCOM/src/bcond_gcn.F
  FVCOM/src/bcond_gcy.F
  FVCOM/src/adjust2d3d.F
  FVCOM/src/brough.F
  FVCOM/src/advection_edge_gcn.F
  FVCOM/src/advection_edge_gcy.F
  FVCOM/src/ghostuv.F
  FVCOM/src/advave_edge_gcn.F
  FVCOM/src/advave_edge_gcy.F
  FVCOM/src/phy_baropg.F
  FVCOM/src/baropg.F
  FVCOM/src/external_step.F
  FVCOM/src/extel_edge.F
  FVCOM/src/extuv_edge.F
  FVCOM/src/depth_check.F
  FVCOM/src/vertvl_edge.F
  FVCOM/src/adv_uv_edge_gcn.F
  FVCOM/src/adv_uv_edge_gcy.F
  FVCOM/src/vdif_uv.F
  FVCOM/src/extelpf_edge.F
  FVCOM/src/wreal.F	
  FVCOM/src/viscofh.F
  FVCOM/src/adv_q.F	
  FVCOM/src/fct_q2.F
  FVCOM/src/fct_q2l.F
  FVCOM/src/vdif_q.F
  FVCOM/src/adv_t.F
  FVCOM/src/adv_s.F
  FVCOM/src/fct_t.F
  FVCOM/src/vdif_ts.F
  FVCOM/src/vdif_ts_gom.F
  FVCOM/src/fct_s.F
  FVCOM/src/bcond_ts.F
  FVCOM/src/adjust_ts.F
  FVCOM/src/conv_over.F
  FVCOM/src/visitsim.F
  FVCOM/src/startup_type.F
  FVCOM/src/edge_len.F
  FVCOM/src/adcor.F
  FVCOM/src/icing.F
  FVCOM/src/rho_pmean.F
  FVCOM/src/calc_vort.F
  FVCOM/src/namelist.F
  FVCOM/src/nh_set_nesting.F
  FVCOM/src/coare26z.F
  FVCOM/src/coare40vn.F
  FVCOM/src/adv_uv_edge_gcn_rk.F
  FVCOM/src/adv_uv_edge_gcy_rk.F
  FVCOM/src/adv_t_rk.F
  FVCOM/src/adv_s_rk.F
  FVCOM/src/adv_q_rk.F)

list(APPEND fvcom_mainw_files
  FVCOM/src/ocpmix.F
  FVCOM/src/ocpcre.F
  FVCOM/src/ocpids.F
  FVCOM/src/swanpre1.F
  FVCOM/src/swanpre2.F
  FVCOM/src/swanser.F
  #FVCOM/src/swanmain.F
  FVCOM/src/swancom1.F
  FVCOM/src/swancom2.F
  FVCOM/src/swancom3.F
  FVCOM/src/swancom4.F
  FVCOM/src/swancom5.F
  FVCOM/src/w3part.F)

list(APPEND fvcom_bio_files
  FVCOM/src/mod_bio_3D.F
  FVCOM/src/mod_onedtide.F)
